In [1]:
import numpy as np

In [2]:
array1 = np.array([[1,2,3],[2,2,3]])
print(type(array1))
print(array1.shape)

<class 'numpy.ndarray'>
(2, 3)


In [3]:
print(array1.ndim)

2


In [4]:
print(array1, array1.dtype)

[[1 2 3]
 [2 2 3]] int64


In [5]:
array2 = np.array([1,2,'test'])
array3 = np.array([1,2,3.0])
print(array2.dtype, array3.dtype)

<U21 float64


In [6]:
array_float = np.array([1.1,2.1,3.1])
array_float2 = array_float.astype('int64')
print(array_float2, array_float2.dtype)

[1 2 3] int64


In [7]:
one_array = np.ones((3,2), dtype='int32')
print(one_array, one_array.dtype)

[[1 1]
 [1 1]
 [1 1]] int32


In [8]:
array1 = np.arange(8)
print(array1)
array2 = array1.reshape(2,2,2)
print(array2)
array3 = array2.reshape(-1,1)
print(array3)
array4 = array3.reshape(-1,1)
print(array4)

[0 1 2 3 4 5 6 7]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


In [9]:
array1 = np.arange(1,10)
a2 = array1.reshape(3,3)
print(a2[2,2])

9


In [10]:
print(a2[0])

[1 2 3]


In [11]:
print(array1[array1>5])

[6 7 8 9]


In [12]:
a1 = np.array([[8,12], [7,1]])
print(a1)
print(np.sort(a1, axis=0))
print(np.sort(a1, axis=1))

[[ 8 12]
 [ 7  1]]
[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


In [13]:
a1 = np.array([3,1,9,4])
si = np.argsort(a1)[::-1]
print(si)


[2 3 0 1]


In [14]:
a = np.array([[1,2,3],[1,4,9]])
b = np.array([[6,3],[4,5],[6,9]])
print(np.dot(a,b))

[[ 32  40]
 [ 76 104]]


In [15]:
print(a)
print(np.transpose(a))

[[1 2 3]
 [1 4 9]]
[[1 1]
 [2 4]
 [3 9]]
